development:
  adapter: postgresql
  database: rails_project_template_development
  host: localhost

test:
  adapter: postgresql
  database: rails_project_template_test
  host: localhost

production:
  adapter: postgresql
  database: rails_project_template_production
  host: localhost
