development:
  adapter: postgresql
  database: rails_project_start_development
  host: localhost

test:
  adapter: postgresql
  database: rails_project_start_test
  host: localhost

production:
  adapter: postgresql
  database: rails_project_start_production
  host: localhost
