development:
  adapter: postgresql
  database: rails_project_development
  host: localhost

test:
  adapter: postgresql
  database: rails_project_test
  host: localhost

production:
  adapter: postgresql
  database: rails_project_production
  host: localhost
